builds:
- id: sazdump
  dir: cmd/sazdump
  binary: sazdump
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
- id: sazserve
  dir: cmd/sazserve
  binary: sazserve
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archives:
- replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
source:
  enabled: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
brews:
- description: Tools for SAZ files (Fiddler logs) - parsing, printing and analyzing using a web page.
  homepage: https://github.com/prantlf/saz-tools
  github:
    owner: prantlf
    name: homebrew-tap
  test: |
    system "#{bin}/sazdump -h"
    system "#{bin}/sazserve -h"
