builds:
- id: sazdump
  dir: cmd/sazdump
  binary: sazdump
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
- id: sazserve
  dir: cmd/sazserve
  binary: sazserve
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
archives:
- replacements:
    darwin: darwin
    linux: linux
    windows: windows
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - man/*
    - README.md
    - LICENSE
source:
  enabled: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
brews:
- description: Parsing, dumping, viewing and analysing tools for SAZ (Fiddler) files
  homepage: https://github.com/prantlf/saz-tools
  github:
    owner: prantlf
    name: homebrew-tap
  commit_author:
    name: Ferdinand Prantl
    email: prantlf@gmail.com
  folder: Formula
  install: |
    bin.install "sazdump"
    bin.install "sazserve"
    man1.install "man/sazdump.1"
    man1.install "man/sazserve.1"
  test: |
    system "#{bin}/sazdump", "-v"
    system "#{bin}/sazserve", "-v"
nfpms:
- description: Parsing, dumping, viewing and analysing tools for SAZ (Fiddler) files
  homepage: https://github.com/prantlf/saz-tools
  maintainer: Ferdinand Prantl <prantlf@gmail.com>
  license: MIT
  vendor: Ferdinand Prantl
  formats:
  - deb
  - rpm
